server:
  port: 8083
spring:
  application:
    name: search-service
  rabbitmq:
    host: ly-mq
    username: guest
    password: guest
    virtual-host: /
  jackson:
    default-property-inclusion: non_null #对象序列化为json字符串的时候看到Null忽略
eureka:
  client:
    service-url:
      defaultZone: http://ly-registry:10086/eureka
logging:
  level:
    com.leyou: debug
ly:
  elasticsearch:
    hosts: http://ly-es:9200